version: '3'
services:
  xco_nginx:
    build: .
    # command: pipenv run python manage.py runserver 0.0.0.0:8000
    command: tail -f /dev/null
    volumes:
      - .:/code
    ports:
      - "80:80"